### ISSUE TITLE
Default %DataFrame.Frame is not a valid Frame

### ISSUE THREAD

**Issue by mbramson** [JordiPolo/dataframe#1]
The defstruct for DataFrame.Frame is not a valid DataFrame.Frame struct if the inspect error is true. It is defined as such:

```
defstruct values: [[]], index: [], columns: []
```

Changing the index default value to [[]] results in a valid Frame, but I'm not sure this is intended. Also, the error message is iffy as it refers to the column key, while changing the index actually resolves the issue.

```
iex(1)> %DataFrame.Frame{}
%Inspect.Error{message: "got ArgumentError with message \"column is not of the right dimmension\" while inspecting %{__struct__: DataFrame.Frame, columns: [], index: [], values: [[]]}"}
iex(2)> %DataFrame.Frame{values: [[]], index: [[]], columns: []}


```

**Comment by mbramson** [comment]
Actually, I'm not sure that's the issue, the Error itself seems a bit wonky. Either way, the default struct should probably be valid!

**Comment by JordiPolo** [comment]
Thank you very much for taking the time to open the issue.
I've pushed a change to master that should solve this issue. Let me know if it solves the issue and we can close this issue or we need more work.
 I'm going to look at your PR, I hope I can base on your test to add a test to cover this case. Thanks!

**Comment by mbramson** [comment]
This looks to be fixed!
